# ===============================
# PRODUCTION CONFIGURATION
# ===============================
spring.application.name=Library-Management

# MySQL - Railway will provide this
spring.datasource.url=${jdbc:mysql://mysql.railway.internal:3306/railway}
spring.datasource.username=${root}
spring.datasource.password=${GgXzknDzNyKCPCXSICEtsoNtlfbdDLMw}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# MongoDB Atlas
spring.data.mongodb.uri=${mongodb+srv://libraryuser:library123@cluster0.scul7lj.mongodb.net/?appName=Cluster0}

# Server
server.port=${PORT:8080}